import { Diamond, FlipHorizontal2, FlipVertical2, RotateCcw, Snowflake } from "lucide-react";
import { defaultAdjustments } from "./editorModel";
import type { Adjustments, TimelineItem } from "./editorModel";
import { addKeyframe } from "./timelineOps";
import { sourceTime } from "./engine/renderFrame";
import "./inspector-tools.css";
const controls:[keyof Adjustments,string,number,number,number][]=[
  ["brightness","Brightness",-.5,.5,.01],["contrast","Contrast",0,2,.01],["saturation","Saturation",0,2,.01],["exposure","Exposure",-3,3,.1],["temperature","Temperature",-1,1,.01],["tint","Tint",-1,1,.01],["highlights","Highlights",-1,1,.01],["shadows","Shadows",-1,1,.01],["vignette","Vignette",0,1,.01],["sharpen","Sharpen",0,1,.01],["grain","Grain",0,1,.01],["blur","Blur",0,30,.5],
];
export function EditorClipTools({item,time,onChange,mode}:{item:TimelineItem;time:number;onChange:(i:TimelineItem)=>void;mode:"basic"|"adjust"}){
  const update=(patch:Partial<TimelineItem>)=>onChange({...item,...patch});
  if(mode==="adjust")return <>
    <section className="editor-inspector-section"><h3>Adjustments<button className="inspector-reset" onClick={()=>update({adjustments:{...defaultAdjustments}})}><RotateCcw size={12}/>Reset</button></h3>
      {controls.map(([key,label,min,max,step])=><div className="adjustment-control" key={key}><label htmlFor={`adjust-${key}`}>{label}</label><output>{((item.adjustments?.[key]??defaultAdjustments[key])).toFixed(step<.1?2:1)}</output><button title={`Keyframe ${label}`} aria-label={`Keyframe ${label}`} onClick={()=>onChange(addKeyframe(item,time,`adjustments.${key}`))}><Diamond size={12}/></button><input id={`adjust-${key}`} aria-label={label} type="range" min={min} max={max} step={step} value={item.adjustments?.[key]??defaultAdjustments[key]} onChange={e=>{
        const next={...item,adjustments:{...item.adjustments,[key]:+e.target.value}};
        onChange(item.keyframes.some(k=>k.values?.[`adjustments.${key}`]!==undefined)?addKeyframe(next,time,`adjustments.${key}`):next);
      }}/></div>)}
    </section>
    <section className="editor-inspector-section"><h3>Blend & mask</h3><label className="editor-field"><span>Blend mode</span><select value={item.blend_mode||"normal"} onChange={e=>update({blend_mode:e.target.value as TimelineItem["blend_mode"]})}>{["normal","multiply","screen","overlay","lighten","darken"].map(v=><option key={v}>{v}</option>)}</select></label><label className="editor-field"><span>Shape mask</span><select value={item.mask?.shape||"none"} onChange={e=>update({mask:{shape:e.target.value as "none"|"circle"|"rectangle",feather:0}})}><option value="none">None</option><option value="circle">Ellipse</option><option value="rectangle">Rounded rectangle</option></select></label></section>
    <section className="editor-inspector-section"><h3>Chroma key</h3><label className="editor-checkbox"><input type="checkbox" checked={item.chroma_key?.enabled||false} onChange={e=>update({chroma_key:{color:"#00ff00",similarity:.2,...item.chroma_key,enabled:e.target.checked}})}/>Remove a background color</label>{item.chroma_key?.enabled&&<><label className="editor-field"><span>Key color</span><input type="color" value={item.chroma_key.color} onChange={e=>update({chroma_key:{...item.chroma_key!,color:e.target.value}})}/></label><label className="editor-field"><span>Color tolerance</span><input type="range" min="0.01" max="0.8" step="0.01" value={item.chroma_key.similarity} onChange={e=>update({chroma_key:{...item.chroma_key!,similarity:+e.target.value}})}/></label></>}</section>
  </>;
  const conceal=item.conceal||{mode:"none" as const,x:5,y:66,width:90,height:18,color:"#101014"};
  return <><section className="editor-inspector-section"><h3>Clip tools</h3><div className="clip-tool-buttons"><button aria-pressed={item.flip_x||false} onClick={()=>update({flip_x:!item.flip_x})}><FlipHorizontal2 size={15}/>Mirror</button><button aria-pressed={item.flip_y||false} onClick={()=>update({flip_y:!item.flip_y})}><FlipVertical2 size={15}/>Flip</button><button aria-pressed={item.reverse||false} onClick={()=>update({reverse:!item.reverse})}><RotateCcw size={15}/>Reverse</button><button aria-pressed={item.freeze_at!=null} onClick={()=>update({freeze_at:item.freeze_at!=null?null:sourceTime(item,time)})}><Snowflake size={15}/>Freeze</button></div><label className="editor-field"><span>Crop edges</span></label><div className="editor-field-pair">{(["top","right","bottom","left"] as const).map(edge=><label className="editor-field" key={edge}><span>{edge[0].toUpperCase()+edge.slice(1)} %</span><input aria-label={`Crop ${edge}`} type="number" min="0" max="45" step="1" value={item.crop?.[edge]||0} onChange={e=>update({crop:{top:0,right:0,bottom:0,left:0,...item.crop,[edge]:Math.max(0,Math.min(45,+e.target.value))}})}/></label>)}</div></section>
  <section className="editor-inspector-section"><h3>Cover existing captions</h3><p>Captions already inside a video are part of the picture. Cover, blur, or crop that area before adding your own.</p><label className="editor-field"><span>Cover method</span><select aria-label="Cover existing captions" value={conceal.mode} onChange={e=>update({conceal:{...conceal,mode:e.target.value as typeof conceal.mode}})}><option value="none">Off</option><option value="cover">Solid cover</option><option value="blur">Blur region</option><option value="mosaic">Pixelate region</option></select></label>{conceal.mode!=="none"&&<><div className="editor-field-pair">{(["x","y","width","height"] as const).map(key=><label className="editor-field" key={key}><span>{key.toUpperCase()} %</span><input aria-label={`Cover ${key}`} type="number" min="0" max="100" value={conceal[key]} onChange={e=>update({conceal:{...conceal,[key]:Math.max(0,Math.min(100,+e.target.value))}})}/></label>)}</div>{conceal.mode==="cover"&&<label className="editor-field"><span>Cover color</span><input type="color" value={conceal.color} onChange={e=>update({conceal:{...conceal,color:e.target.value}})}/></label>}</>}</section></>;
}
